### ISSUE TITLE
More featureful searchFor hints and action specific searchFor hints

### ISSUE THREAD

**Issue by LauJosefsen** [cego/git-local-devops#63]
For example the last line from a script may say something like
```happytiger-dev environment: { name: happytiger.co.uk-dev, url: https://gamesearch-lejo.greathippydev.dk }```

I suggest having a config along the lines of:
```yml
searchFor: 
  - regex: "-dev environment: { name: ([^.]*).*-dev, url: (.*) }"
    hint: "{green {1} gamesearch service has started sucessfully - go visit it on} {cyan {2}}"
```
From which, if the regex matches any stdout output from that action, it should print
![image](https://user-images.githubusercontent.com/44977457/161406059-0a7cb7ed-55d5-47c3-8ea8-5ef50866d820.png)

I think this config should sit on the action itself OR global.

Implemented in #64
